name: self_secure
description: "SELF SECURE - Personal Security & Device Protection"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Local security settings and PIN storage
  shared_preferences: ^2.5.3

  # Fingerprint / Face ID / device authentication
  local_auth: ^2.3.0

  # Device information
  device_info_plus: ^11.5.0

  # Battery information
  battery_plus: ^6.2.2

  # Real GPS / location
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
